# Generated by Django 5.2.17 on 2026-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("other", "Other"),
                        ],
                        default="youtube",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="clips/"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_headline", models.CharField(default="STEERS", max_length=40)),
                ("hero_tag", models.CharField(default="COMEDY", max_length=40)),
                (
                    "hero_subline",
                    models.CharField(default="LIVE. LOUD. SOLD OUT.", max_length=80),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="Stand-up from Mexico City and wherever the next flight goes."
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Background photo for the hero section. Ignored if a hero video is set.",
                        null=True,
                        upload_to="hero/",
                    ),
                ),
                (
                    "hero_video",
                    models.FileField(
                        blank=True,
                        help_text="Optional background video (MP4, ideally under ~15MB, no audio). Takes priority over the hero photo when set.",
                        null=True,
                        upload_to="hero/",
                    ),
                ),
                (
                    "about_heading",
                    models.CharField(default="Same guy. Louder room.", max_length=80),
                ),
                (
                    "about_body",
                    models.TextField(
                        default="Steers has spent a few too many years turning very normal life experience into stand-up that is, according to at least one heckler, unreasonably funny. Based in Mexico City, performing everywhere that will have him."
                    ),
                ),
                (
                    "about_photo",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "about_quote",
                    models.CharField(
                        blank=True,
                        default='"Actually pretty good." — a friend, probably',
                        max_length=160,
                    ),
                ),
                (
                    "site_tagline",
                    models.CharField(
                        default="Stand-up comedy from Steers.", max_length=80
                    ),
                ),
                (
                    "footer_note",
                    models.CharField(
                        blank=True,
                        default="Steers Comedy",
                        help_text="Shown in the footer next to the copyright year.",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "verbose_name": "Home page content",
                "verbose_name_plural": "Home page content",
            },
        ),
        migrations.CreateModel(
            name="ShowRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "venue_city",
                    models.CharField(max_length=160, verbose_name="Venue / city"),
                ),
                ("preferred_dates", models.CharField(blank=True, max_length=160)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Show request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("x", "X"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "platform"],
            },
        ),
        migrations.CreateModel(
            name="TourDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("ticket_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
