# Generated by Django 5.2.17 on 2026-08-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ig_user_id",
                    models.CharField(
                        blank=True,
                        help_text="The numeric Instagram user ID for the professional (Business or Creator) account to pull posts from.",
                        max_length=60,
                        verbose_name="Instagram user ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        help_text="A long-lived Instagram access token for that account. Expires roughly every 60 days — see the README for how to renew it.",
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set automatically (assumes 60 days) when you paste in a new token, or precisely by the refresh_instagram_token command.",
                        null=True,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Turn off to stop pulling from Instagram and fall back to the manually-added Clips below, without losing the saved token.",
                    ),
                ),
                (
                    "max_posts",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="How many recent posts to show in the Clips section.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram settings",
                "verbose_name_plural": "Instagram settings",
            },
        ),
    ]
