# Generated by Django 5.2.17 on 2026-09-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedy", "0002_instagramsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("youtube", "YouTube"),
                    ("x", "X"),
                    ("cdmxcomedyfest", "CDMX Comedy Fest"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
